name: ChestTerminal Remake
version: ${project.version}
authors: [ TheBusyBiscuit, scbm187531, aoad ]
website: https://github.com/TheBusyBiscuit/ChestTerminal

api-version: 1.14
main: io.github.thebusybiscuit.chestterminal.ChestTerminal

depend:
- Slimefun
